name: Build and Deploy (manual)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        type: choice
        required: true
        options:
        - dev
        - preprod
        - prod

jobs:
  Build:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: display
        run: |
          echo ${{ github.event.inputs.environment }}
          echo vega-docker-${{ github.event.inputs.environment}}.docker.artifactory.viasat.com ehrcui latest

    
